accounts/urls.py
from django.conf.urls import url
from . import views


app_name = 'accounts'
urlpatterns = [
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^login/$', views.login_view, name='login_view'),
    url(r'^logout/$', views.logout_view, name='logout_view'),
    url(r'^profile/$', views.profile_view, name='profile_view'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    url(r'^account_activation_sent/$', views.account_activation_sent, name='account_activation_sent'),
]

authors/urls.py
from django.conf.urls import url
from .views import (
    author_detail,
    author_new,
    author_edit,
    author_delete
)

app_name = 'authors'
urlpatterns = [
    url(r'^author/(?P<pk>\d+)/$', author_detail, name='author_detail'),
    url(r'^author/new/$', author_new, name='author_new'),
    url(r'^author/(?P<pk>\d+)/edit/', author_edit, name='author_edit'),
    url(r'^author/(?P<pk>\d+)/delete', author_delete, name='author_delete')
]

books/urls.py
from django.conf.urls import url
from .views import (
    book_detail,
    book_new,
    book_edit,
    book_delete,
)

app_name = 'books'
urlpatterns = [
    url(r'^book/(?P<pk>\d+)/$', book_detail, name='book_detail'),
    url(r'^book/new/$', book_new, name='book_new'),
    url(r'^book/(?P<pk>\d+)/edit/', book_edit, name='book_edit'),
    url(r'^book/(?P<pk>\d+)/delete', book_delete, name='book_delete'),
]

mysite/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('index.urls', namespace='index')),
    url(r'^book/', include('books.urls', namespace='books')),
    url(r'^author/', include('authors.urls', namespace='authors')),
    url(r'^accounts/', include('accounts.urls', namespace="accounts")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/models.py
from django.db import models
from authors.models import Author
from django.utils import timezone
from django.contrib.auth.models import AbstractUser
from django.conf import settings


class Book(models.Model):
    title = models.CharField(max_length=200, unique=True)
    description = models.TextField()
    post_author = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.CASCADE)
    year_issued = models.SmallIntegerField()
    authors = models.ManyToManyField(Author, blank=True)
    tags = models.TextField(default="")
    publication_no = models.SmallIntegerField(default='1')
    isbn = models.SmallIntegerField()
    book_cover = models.ImageField(upload_to='pics/', default='pics/None/no_cover.png')
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def save(self, **kwargs):
        self.published_date = timezone.now()
        super(Book, self).save(**kwargs)

    def approved_reviews(self):
        return self.reviews.filter(approved_review=True)

    def __str__(self):
        return self.title

index/templates/index/base.html
{% load staticfiles %}
<html>

    <head>
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
		<link href="https://fonts.googleapis.com/css?family=Lobster&subset=latin,cyrillic" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css?family=Tangerine&subset=latin,cyrillic" rel="stylesheet" type="text/css">
		<link rel="stylesheet" href="{% static 'css/index.css' %}">
        <title>Book WORM</title>
        {% if user.is_authenticated %}
            <div class="logged-user">
                <a href="{% url 'accounts:profile_view' %}">Welcome, {{ user.email }}!  </a>
                <a href="{% url 'accounts:logout_view' %}">Logout</a>
            </div>
        {% else %}
            <div class="logged-user">
                <a href="{% url 'accounts:login_view' %}">Login</a>
                <a href="{% url 'accounts:signup' %}">Signup</a>
            </div>
        {% endif %}
    </head>
    <body>
		<div class="page-header">
			{% if user.is_authenticated %}
				<a href="{% url 'books:book_new' %}" title="Добавить книгу" class="top-menu"><span class="glyphicon glyphicon-book"></span></a>
                <a href="{% url 'authors:author_new' %}" title="Добавить автора" class="top-menu"><span class="glyphicon glyphicon-pencil"></span></a>
			{% endif %}
			<h1><a href="/">Книжный червь</a></h1>
		</div>
		<div class="content container">
				<div class="row">
				<div class="col-md-8">
				{% block content %}
				{% endblock %}
				</div>
			</div>
		</div>


    </body>
</html>

index/templates/index/index.html
{% extends 'index/base.html' %}


{% block content %}

        <h2>Выборка книг</h2>
        {% for book in books_all %}
            <div class="books_index">
                <h2><a href="{% url 'books:book_detail' pk=book.pk %}">{{ book.title }}</a></h2>
                <p>{{ book.description|linebreaksbr }}</p>
                <p><b>Authors:</b> {% for author in book.authors.all %}{{ author }}{% if author != book.authors.last %}{{ ", " }}{% endif %}{% endfor %}.</p>
            </div>
        {% endfor %}
    <br>
        <h2>Выборка авторов</h2>
        {% for author in authors_all %}
            <div class="authors_index">
                <h2><a href="{% url 'authors:author_detail' pk=author.pk %}">{{ author.name }}</a></h2>
                <p><b>Books:</b> {% for title in author.book_set.all %}{{ title }}{% if title != author.book_set.last %}{{ ", " }}{% endif %}{% endfor %}.</p>
            </div>
        {% endfor %}





{% endblock %}